server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{URL}}
    username: ${{MASTER}}
    password: ${{PASSWORD}}

  jpa:
    hibernate:
      ddl-auto: create #create -> update
    show-sql: true
    properties:
      hibernate:
        format_sql:true
jwt:
  secret-key: ${{JWT}}

oauth:
  kakao:
    client-id: ${{ KAKAO_ID }}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com

  mvc:
    path match:
      matching-strategy: ant_path_matcher
    format:
      date-time: yyyy-MM-dd HH:mm:ss